---
name: 01 Azure Landing Zone Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: teroeorg5431/alz-mgmt-templates/.github/workflows/ci_template.yaml@main
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
